kind: pipeline
type: docker
name: integration

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk
    commands:
      - dotnet build

  - name: test
    image: mcr.microsoft.com/dotnet/sdk
    commands:
      - dotnet test 

  - name: sonarqube
    image: sonarsource/sonar-scanner-cli:latest
    settings:
      sonar.host.url: http://sonarqube.example.com
    commands:
      - sonar-scanner

services:
  - name: sonarqube
    image: sonarqube:latest
